version: '3'

services:
  db:
    image: postgres
    volumes:
      - db-volume:/data/postgres
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - DJANGO_SECRET_KEY=aaaaaaaaaaaaaaaa
    depends_on:
      - db
    restart: always

volumes:
  db-volume:
